version: '3.7'

networks:
    laravel:
        driver: bridge
        
services:
    php:
        build:
            args:
                user: test
                uid: 1000
            context: .
            dockerfile: Dockerfile
        container_name: php
        ports:
            - 9000:9000
        volumes:
            - .:/var/www/html:delegated
        restart: unless-stopped
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - 8088:80
        volumes:
            - .:/var/www/html:delegated
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
            - elasticsearch
        restart: unless-stopped
        networks:
            - laravel

    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - 4306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        restart: unless-stopped
        tty: true
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        depends_on:
            - mysql
        restart: always
        networks:
            - laravel

    npm:
        image: node:latest
        container_name: npm
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel
            
    elasticsearch:
        image: elasticsearch:7.13.1
        environment:
            - "discovery.type=single-node"
            - cluster.routing.allocation.disk.threshold_enabled=false
            - "bootstrap.memory_lock=true"
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
        networks:
            - laravel
